version: '3.9'

services:
  db:
    build: ./postgres
    image: postgres-db
    volumes:
      - './postgres/data:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: postgres
  
  backend:
    depends_on:
      - db
    build: ./backend
    image: node:latest
    volumes:
      - './backend:/usr/src/app'
    # command: ["/bin/bash"]
    ports:
      - "3030:3000"
    tty: true
    # tty -> docker 컨테이너 특성상, 커맨드가 끝나면 컨테이너가 종료된다. 이를 방지하기 위해서 tty 옵션을 docker-compose에 사용할 수 있다.
    # docker run -it 에서
    # -i 는 stdin_open: true 로 사용 가능하고
    # -t 는 tty: true 로 사용 가능하다
    # stdin_open: true
    environment:
      - DBHOST=db

  frontend:
    depends_on:
      - backend
    build: ./frontend
    image: nginx:1.19
    volumes:
      - './frontend:/home/www'
    ports:
      - "8080:8080"

  influxdb:
    image: influxdb:1.8
    build: ./influxdb
    ports:
      - '8788:8086'
    volumes:
      - './influxdb:/var/lib/influxdb'
      - './influxdb.conf:/etc/influxdb/influxdb.conf'
    environment:
      INFLUX_DB_ID: influx
      INFLUX_DB_PASSWORD: influx
    # #networks:
    #   - influx-grafana
  
  grafana:
    depends_on:
      - influxdb
    image: grafana/grafana:8.1.2
    build: ./grafana
    ports:
      - '3000:3000'
    volumes:
      - './grafana/var_lib_grafana:/var/lib/grafana'
      # - './grafana/etc_grafana/grafana.ini:/etc/grafana/grafana.ini:ro'
    #networks:
      # - influx-grafana

  telegraf:
    # depends_on:
    #   - influxdb
    image: telegraf
    # ports:
    #   - 8092:8092
    volumes:
      - './telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro'
    #networks:
      # - influx-grafana

  simulator-server:
    build:
      context: ./mqtt
    image: node-binary:simulator
    volumes:
      - './mqtt/volume:/home/server'
    command: ["/bin/bash"]
    ports:
      - "3002:3000"
    tty: true
    stdin_open: true
    #networks:
      # - webnet

  mqtt:
    image: eclipse-mosquitto
    hostname: mosquitto
    restart: always
    ports:
      - "1834:1883"
      # - "8089:8088"
    volumes: 
      - ./mqtt/mqtt/config:/mosquitto/config
    tty: true
    stdin_open: true
<<<<<<< HEAD
    #networks:
      # - webnet
      # - influx-grafana
# #networks:
#   webnet:
#   influx-grafana:
=======
    networks:
      - webnet
networks:
  webnet:
  influx-grafana:
>>>>>>> 159c631805162cdfbf73a49216e375d32a6bd3b4
